### ISSUE TITLE
Change loader from 'python' to 'python3'

### ISSUE THREAD

**Issue by stuaxo** [killarny/gedit-python-outline#4]
In pythonoutline.plugin lets the plugin load (tested on Ubuntu Utopic)

**Comment by killarny** [comment]
I have a feature branch where this change was made, but I haven't worked on it since I switched to using PyCharm instead of gedit:

[feature/gnome3.8-support](https://github.com/killarny/gedit-python-outline/commits/feature/gnome3.8-support)

I'm not at all certain what state that feature branch is in, but if it's at a good point to move forward from, then I should probably merge it to master.

See also #3
